// <auto-generated />
using System;
using CleanArchitectureTemplate.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchitectureTemplate.Persistence.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20250112203925_Concurrency")]
    partial class Concurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct", "Marketing");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Common.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Persistence.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Persistence.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.CategoryImageFile", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileDetailsId")
                        .HasColumnType("uuid");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FileDetailsId");

                    b.ToTable("CategoryImageFiles", "Files");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileType");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StorageType");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FileDetails_Name");

                    b.ToTable("FileDetails", "Files");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.InvoiceFile", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("FileDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.HasIndex("FileDetailsId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceFiles", "Files");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.ProductImageFile", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("FileDetailsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasIndex("FileDetailsId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImageFiles", "Files");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.ReportFile", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("FileDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ReportType");

                    b.HasIndex("FileDetailsId");

                    b.ToTable("ReportFiles", "Files");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.UserAvatarFile", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("FileDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("FileDetailsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAvatarFiles", "Files");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Marketing.Category", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Categories_Name");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", "Marketing");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StandardPrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("StoreId");

                    b.ToTable("Products", "Marketing");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Membership.Customer", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers", "Membership");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Membership.Store", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Stores", "Membership");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.Invoice", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices", "Ordering");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.Order", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders", "Ordering");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.OrderItem", b =>
                {
                    b.HasBaseType("CleanArchitectureTemplate.Domain.Common.BaseEntity");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "Ordering");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.CategoryImageFile", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", "FileDetails")
                        .WithMany()
                        .HasForeignKey("FileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.CategoryImageFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FileDetails");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.InvoiceFile", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", "FileDetails")
                        .WithMany()
                        .HasForeignKey("FileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.InvoiceFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Ordering.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetails");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.ProductImageFile", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", "FileDetails")
                        .WithMany()
                        .HasForeignKey("FileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.ProductImageFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", "Product")
                        .WithMany("ProductImageFiles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetails");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.ReportFile", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", "FileDetails")
                        .WithMany()
                        .HasForeignKey("FileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.ReportFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetails");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Files.UserAvatarFile", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Files.FileDetails", "FileDetails")
                        .WithMany()
                        .HasForeignKey("FileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.UserAvatarFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Files.UserAvatarFile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetails");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Marketing.Category", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Marketing.Category", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Membership.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Membership.Customer", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Membership.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Membership.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Membership.Store", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Membership.Store", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Persistence.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Membership.Store", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.Invoice", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Ordering.Invoice", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Ordering.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CleanArchitectureTemplate.Domain.ValueObjects.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("OrderId");

                            b1.ToTable("BillingAddress", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.Order", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Membership.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Ordering.Order", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", null)
                        .WithMany("Orders")
                        .HasForeignKey("ProductId");

                    b.OwnsOne("CleanArchitectureTemplate.Domain.ValueObjects.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("OrderId");

                            b1.ToTable("ShippingAddresses", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.OrderItem", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Domain.Common.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("CleanArchitectureTemplate.Domain.Entities.Ordering.OrderItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Ordering.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Marketing.Product", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductImageFiles");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Membership.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Membership.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.Ordering.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
